# Generated by Django 4.2.13 on 2024-05-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1046_workflowaction_remove_all_correspondents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("ar", "Arabe")],
                default="fr",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="link_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.document",
            ),
        ),
    ]
